language: julia
sudo: true

os:
    - linux

notifications:
    email: false

julia:
  - 1.4

addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD='xvfb-run julia'; else TESTCMD='julia'; fi
    - $TESTCMD -e 'using Pkg; Pkg.build()'
    
jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - xvfb-run julia --project=docs/ docs/make.jl
      after_success: skip